// <auto-generated />
using System;
using Carrito.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carrito.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carrito.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id")
                        .HasName("PK__Authors__3214EC0741AF68BB");

                    b.HasIndex(new[] { "FullName" }, "UQ__Authors__89C60F119BF29D3E")
                        .IsUnique();

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("Carrito.Models.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarritoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioPersonaId")
                        .HasColumnType("int");

                    b.HasKey("CarritoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UsuarioPersonaId");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Carrito.Models.CarritoLibro", b =>
                {
                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<int>("LibroId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("CarritoId", "LibroId");

                    b.HasIndex("LibroId");

                    b.ToTable("CarritoLibros");
                });

            modelBuilder.Entity("Carrito.Models.Domicilio", b =>
                {
                    b.Property<int>("DomicilioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomicilioId"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("PisoDepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DomicilioId");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("Domicilio");
                });

            modelBuilder.Entity("Carrito.Models.Editorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id")
                        .HasName("PK__Publishe__3214EC07B1F2861C");

                    b.HasIndex(new[] { "Name" }, "UQ__Publishe__737584F67DA8EECF")
                        .IsUnique();

                    b.ToTable("Editorial", (string)null);
                });

            modelBuilder.Entity("Carrito.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Genres__3214EC07250568B3");

                    b.HasIndex(new[] { "Name" }, "UQ__Genres__737584F6C2A08496")
                        .IsUnique();

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("Carrito.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("Pages")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("SynopsisEs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Books__3214EC07AFED810F");

                    b.HasIndex("PublisherId");

                    b.HasIndex(new[] { "AuthorId" }, "IX_Books_AuthorId");

                    b.HasIndex(new[] { "GenreId" }, "IX_Books_GenreId");

                    b.HasIndex(new[] { "Title" }, "IX_Books_Title");

                    b.ToTable("Libro", (string)null);
                });

            modelBuilder.Entity("Carrito.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Carrito.Models.Usuario", b =>
                {
                    b.HasBaseType("Carrito.Models.Persona");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CarritoId");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Carrito.Models.Carrito", b =>
                {
                    b.HasOne("Carrito.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Carrito.Models.Usuario", null)
                        .WithMany("HistorialCompra")
                        .HasForeignKey("UsuarioPersonaId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Carrito.Models.CarritoLibro", b =>
                {
                    b.HasOne("Carrito.Models.Carrito", "Carrito")
                        .WithMany("Libros")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carrito.Models.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("Carrito.Models.Domicilio", b =>
                {
                    b.HasOne("Carrito.Models.Persona", "Persona")
                        .WithOne("Domicilio")
                        .HasForeignKey("Carrito.Models.Domicilio", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Carrito.Models.Libro", b =>
                {
                    b.HasOne("Carrito.Models.Autor", "Author")
                        .WithMany("Libros")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Books_Authors");

                    b.HasOne("Carrito.Models.Genero", "Genre")
                        .WithMany("Libros")
                        .HasForeignKey("GenreId")
                        .IsRequired()
                        .HasConstraintName("FK_Books_Genres");

                    b.HasOne("Carrito.Models.Editorial", "Publisher")
                        .WithMany("Libros")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_Books_Publishers");

                    b.Navigation("Author");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Carrito.Models.Usuario", b =>
                {
                    b.HasOne("Carrito.Models.Carrito", "Carrito")
                        .WithMany()
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("Carrito.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Carrito.Models.Carrito", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Carrito.Models.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Carrito.Models.Genero", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("Carrito.Models.Persona", b =>
                {
                    b.Navigation("Domicilio")
                        .IsRequired();
                });

            modelBuilder.Entity("Carrito.Models.Usuario", b =>
                {
                    b.Navigation("HistorialCompra");
                });
#pragma warning restore 612, 618
        }
    }
}
